/** A student passed 3 exams and received 3 grades on a 10-points scale.
 * The grades for each exam are generated by the program randomly.
 * The program evaluates whether the student's performance was good or bad.
 */
public class ExamGrade {
    public static void main(String[]args){

        int mathematics = (int)(Math.random()*10);
        int physics = (int)(Math.random()*10);
        int english = (int)(Math.random()*10);

        if (mathematics < 5){
            System.out.println("Mathematics - Bad");
        } else {
            System.out.println("Mathematics - Good");
        }

        if (physics < 5){
            System.out.println("Physics - Bad");
        } else {
            System.out.println("Physics - Good");
        }

        if (english < 5){
            System.out.println("English - Bad");
        } else {
            System.out.println("English - Good");
        }
    }
}
